language: generic
include:
- os: linux
  addons:
    apt:
      update: true
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - debootstrap
      - genisoimage
      - p7zip-full
      - squashfs-tools
      - ubuntu-dev-tools
      - dpkg-dev
      - debhelper
      - fakeroot
      - devscripts
      - jq
sudo: required
dist: xenial
git:
  depth: 22
script:
- export LC_ALL=en_US.UTF-8
- export LANG=en_US.UTF-8
- export LANGUAGE=en_US.UTF-8
- chmod +x ./build.sh
- "./build.sh |& tee log.txt"
before_deploy:
- export image_name="`echo *.iso`"
- cat *.iso > "/home/travis/${image_name}"
- cp log.txt /home/travis/log.txt
notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: SIHghwYy1r0ItI1pgKYDKpJyih9RwladD+hPBWD+qPZ4b0mf0eqGpvJdlZRh8Hic+qQ5UuUzKjv4oqrC8yc4paf1GXvLMX3iga0f7N2RapPA7n353jWzH30olKqygLJAyDTadaDO1PBgX7h80ImURS6Vr0hVlgMg2KhYPMDjet4G9wrJttgflKqHrqnaPthC2YAXKtYMwskcyXIU9xs180ooUJ+M4ikKjAwQaLX+C0N+MtMejttausCKepn/qrAhBHfJ1RMbdLbkWqHmu1CE0lt1EaAub4OQVERrknae6g0Oi6/mO+3od9e9pV9RjSHXk8ZJywnUy8XwArYL7Fa7hTjmAFw68NGpbiUMd+XylbriC3uInc8/qPCvco/+k4rCl+G5I07/Q+v3NqU9sZ68fxGJg+6GzEzQqVeQXMLEQJqjDVZf+8T01s2AfgZPce9RgYqU38pk9Fo+D82vY3JneO9TkDx5+oe5JEJEbSC5ogSsT0uIWVgYaytWVA5x0LkkOUlrxJUet4Ji7kHCixE2kEvLSSVthLkc3J27/A7yTZU8gEs4ZaXsL/quctuYThvC9zBzWLhgS3WBxl8a6risZyNxkDioM+O4NtfB4KtMyGnvl9dlFKDDkXqE3u3FmwDZrzbpUlwthr/tOqj2+AaYvKli2kvLVVbcayULYzktLm8=
  file_glob: true
  file:
  - "/home/travis/${image_name}"
  - "/home/travis/log.txt"
  on:
    all_branches: true
after_deploy:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/releases_maintainer.sh;
  fi
- cd scripts/mail-scripts && ./mail.py
after_failure:
- cd scripts/mail-scripts && ./mail-fail.py
env:
  global:
    secure: ZEIq6w9brECxhwKQ8SOu5tel7qBdI8Td0gdcMog8GMHqxaYEGBLE/BC0eUDUOpwHmVkOfAGsNGcUxRFpgouqW3FvMPDO6SMQnh60VXWkH1sQMK1LQfOsJuP6sHwBYp5jvPIBxmtpPHD2MuuMlK76TuR3ZlLAPSyKdUI7Q7Hf1y060k7301QgM6K51o6zfKgplN7IUAjue9msRBeiPuLUA7Y9reN1hRhQwudi4tSQl8Rc2YX5bP0jPb4JB1stmZh9/0M4G699k5oMIQXJo17GXnhn2xgxwzoLcuc828hC9nCVMqY10S6V128+hrb8nBrNVzhS25aDsiHgnpYV8OQVkB+wCihJvsO6A9VNxfaLrcPgyN7qWwIV1QNH7z/a2BFS+gMYAtzY82yFHL6jFSkuRujLDLv7PCB+mqyg+hEPkQ8aBjFJIyVKJg6tETqfD7soEe//HWSDpeSzJ0la0Tf6DJ5IQHeJ6llvG8V/TYXdFodSlTsIyvu/PB9hgF7bRVcuwEvRdsnA/E/UAO7OrWiib9/sSKsDZtVORCl/tIkh0erwd2JBAjMuTrUiETFK2MFSVGbuTFyK0jBLW3j6WcLPIbqXJMuY/5zqgjG0aodvAQtqu/iTkufGEhcTuofH1IV4e1y2o3t4d8jI4NsPjjn7md2t1l+GWVmZK+eBn7yI0gQ=
